-- ----------------------------
-- Table structure for PLT_BASE_CODE_RULE
-- ----------------------------
CREATE TABLE PLT_BASE_CODE_RULE (
  PKID VARCHAR2(32 BYTE) NOT NULL ,
  RULE_CODE VARCHAR2(40 BYTE) NULL ,
  RULE_NAME VARCHAR2(60 BYTE) NULL ,
  BELONG_BUSINESS VARCHAR2(64 BYTE) NULL ,
  CODE_TYPE VARCHAR2(40 BYTE) NULL ,
  EFFECTIVE_DATE DATE NULL ,
  EXPIRATION_DATE DATE NULL ,
  BELONG_ORG_PKID VARCHAR2(32 BYTE) NULL ,
  SYSTEM_CODE VARCHAR2(32 BYTE) NULL ,
  EXT0 VARCHAR2(40 BYTE) NULL ,
  EXT1 VARCHAR2(200 BYTE) NULL ,
  REMARK VARCHAR2(1500 BYTE) NULL ,
  FLAG_STATUS NUMBER(4) NULL ,
  FLAG_SORT NUMBER(20) NULL ,
  FLAG_DELETE NUMBER(4) NULL ,
  FLAG_DELETE_TOKEN VARCHAR2(32 BYTE) DEFAULT '0',
  FLAG_VERSION NUMBER(20) NULL ,
  FLAG_AUDIT NUMBER(4) NULL ,
  AUDIT_PID VARCHAR2(40 BYTE) NULL ,
  MAKE_USER VARCHAR2(32 BYTE) NULL ,
  MAKE_TIME DATE NULL ,
  MODIFY_USER VARCHAR2(32 BYTE) NULL ,
  MODIFY_TIME DATE NULL ,
  COMP_PKID VARCHAR2(32 BYTE) NULL ,
  MODULE_CODE VARCHAR2(32 BYTE) NULL
);

COMMENT ON TABLE PLT_BASE_CODE_RULE IS '平台-基础数据管理-编码规则';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.PKID IS '主键';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.RULE_CODE IS '规则编码';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.RULE_NAME IS '规则名称';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.BELONG_BUSINESS IS '所属业务';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.CODE_TYPE IS '编码类型';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.EFFECTIVE_DATE IS '生效日期';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.EXPIRATION_DATE IS '失效日期';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.BELONG_ORG_PKID IS '所属组织(可是部门、工厂、车间、公司等)';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.SYSTEM_CODE IS '扩展字段，多系统情况下区分所属系统，一般平台通用表常用';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.EXT0 IS '扩展字段';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.EXT1 IS '扩展字段1';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.REMARK IS '描述、备注，默认长度500，如果特殊表长度不够用，可自己酌情调整。';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.FLAG_STATUS IS '【系统提供】默认有效，有效状态（封存状态、启用状态）。0-无效；1-有效。还可以扩展其他值，默认由框架自动填充为1，开发人员可以手工覆盖。';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.FLAG_SORT IS '【系统提供】自定义排序字段，整数，需要手工排序时使用';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.FLAG_DELETE IS '【系统提供】逻辑删除标记，0-正常；1-逻辑删除。几乎全部查询的where条件都要加上这个条件，默认由框架自动填充为0，开发人员可以手工覆盖';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.FLAG_DELETE_TOKEN IS '删除标记位';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.FLAG_VERSION IS '【系统提供】用于并发修改控制，可以存时间戳';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.FLAG_AUDIT IS '【系统提供】审核标识。-1-废弃；0-没进入审核；1-审核中；2-审核通过；3-审核未通过';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.AUDIT_PID IS '【系统提供】记录审核流中流程实例id，方便查询。工作流引擎负责写入，不用开发人员维护';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.MAKE_USER IS '【系统提供】由框架自动填充当前登录人pk_id';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.MAKE_TIME IS '【系统提供】由框架自动填充当前系统时间';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.MODIFY_USER IS '【系统提供】由框架自动填充当前登录人pk_id';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.MODIFY_TIME IS '【系统提供】由框架自动填充当前系统时间';
COMMENT ON COLUMN PLT_BASE_CODE_RULE.COMP_PKID IS '【系统提供】操作人所属公司，几乎全部查询的where条件都要加上这个条件，默认由框架自动填充（取当前所在公司），开发人员可以手工覆盖';

-- ----------------------------
-- Indexes structure for table PLT_BASE_CODE_RULE
-- ----------------------------
CREATE INDEX PLT_BASE_CODE_RULE_IDX1 ON PLT_BASE_CODE_RULE (RULE_CODE);
CREATE INDEX PLT_BASE_CODE_RULE_IDX2 ON PLT_BASE_CODE_RULE (FLAG_DELETE);
CREATE INDEX PLT_BASE_CODE_RULE_IDX3 ON PLT_BASE_CODE_RULE (FLAG_VERSION);

-- ----------------------------
-- Checks structure for table PLT_BASE_CODE_RULE
-- ----------------------------
ALTER TABLE PLT_BASE_CODE_RULE ADD CHECK (PKID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PLT_BASE_CODE_RULE
-- ----------------------------
ALTER TABLE PLT_BASE_CODE_RULE ADD PRIMARY KEY (PKID);

-- ----------------------------
-- Unique Union Index structure for table PLT_BASE_CODE_RULE_SERIAL
-- ----------------------------
ALTER TABLE PLT_BASE_CODE_RULE ADD CONSTRAINT PLT_BASE_CODE_RULE_CST1 UNIQUE (RULE_CODE, SYSTEM_CODE, FLAG_DELETE_TOKEN);






-- ----------------------------
-- Table structure for PLT_BASE_CODE_RULE_DETAIL
-- ----------------------------
CREATE TABLE PLT_BASE_CODE_RULE_DETAIL (
  PKID VARCHAR2(32 BYTE) NOT NULL ,
  HEAD_PKID VARCHAR2(32 BYTE) NULL ,
  SECTION_TYPE VARCHAR2(32 BYTE) NULL ,
  SECTION_VALUE VARCHAR2(64 BYTE) NULL ,
  SECTION_LENGTH NUMBER(4) NULL ,
  SUPPLY_TYPE VARCHAR2(32 BYTE) NULL ,
  SUPPLY_CHAR VARCHAR2(32 BYTE) NULL ,
  DATE_FORMAT VARCHAR2(40 BYTE) NULL ,
  FLAG_SERIAL NUMBER(4) NULL ,
  FLAG_SHOW NUMBER(4) NULL ,
  SECTION_SEPARATOR VARCHAR2(2 BYTE) NULL ,
  EXT0 VARCHAR2(40 BYTE) NULL ,
  EXT1 VARCHAR2(200 BYTE) NULL ,
  FLAG_STATUS NUMBER(4) NULL ,
  FLAG_SORT NUMBER(20) NULL ,
  FLAG_DELETE NUMBER(4) NULL ,
  FLAG_DELETE_TOKEN VARCHAR2(32 BYTE) DEFAULT '0',
  FLAG_VERSION NUMBER(20) NULL ,
  FLAG_AUDIT NUMBER(4) NULL ,
  AUDIT_PID VARCHAR2(40 BYTE) NULL ,
  MAKE_USER VARCHAR2(32 BYTE) NULL ,
  MAKE_TIME DATE NULL ,
  MODIFY_USER VARCHAR2(32 BYTE) NULL ,
  MODIFY_TIME DATE NULL ,
  COMP_PKID VARCHAR2(32 BYTE) NULL ,
  SYSTEM_CODE VARCHAR2(32 BYTE) NULL ,
  MODULE_CODE VARCHAR2(32 BYTE) NULL
);
COMMENT ON TABLE PLT_BASE_CODE_RULE_DETAIL IS '平台-基础数据管理-编码规则-子表';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.PKID IS '主键';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.HEAD_PKID IS '编码规则主表主键';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.SECTION_TYPE IS '段类型，枚举值， 常量、系统变量、字段值、自定义SQL、流水号。';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.SECTION_VALUE IS '段值';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.SECTION_LENGTH IS '段长度';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.SUPPLY_TYPE IS '补位方式';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.SUPPLY_CHAR IS '补位字符';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.FLAG_SERIAL IS '流水依据， 1 ：是流水依据；0：不是流水依据';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.FLAG_SHOW IS '是否显示，显示：1，0：不显示';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.SECTION_SEPARATOR IS '段分隔符（两个字符）';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.EXT0 IS '扩展0';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.EXT1 IS '扩展1';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.FLAG_STATUS IS '【系统提供】默认有效，有效状态（封存状态、启用状态）。0-无效；1-有效。还可以扩展其他值，默认由框架自动填充为1，开发人员可以手工覆盖。';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.FLAG_SORT IS '【系统提供】自定义排序字段，整数，需要手工排序时使用';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.FLAG_DELETE IS '【系统提供】逻辑删除标记，0-正常；1-逻辑删除。几乎全部查询的where条件都要加上这个条件，默认由框架自动填充为0，开发人员可以手工覆盖';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.FLAG_DELETE_TOKEN IS '删除标记位';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.FLAG_VERSION IS '【系统提供】用于并发修改控制，可以存时间戳';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.FLAG_AUDIT IS '【系统提供】审核标识。-1-废弃；0-没进入审核；1-审核中；2-审核通过；3-审核未通过';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.AUDIT_PID IS '【系统提供】记录审核流中流程实例id，方便查询。工作流引擎负责写入，不用开发人员维护';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.MAKE_USER IS '【系统提供】由框架自动填充当前登录人pk_id';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.MAKE_TIME IS '【系统提供】由框架自动填充当前系统时间';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.MODIFY_USER IS '【系统提供】由框架自动填充当前登录人pk_id';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.MODIFY_TIME IS '【系统提供】由框架自动填充当前系统时间';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_DETAIL.COMP_PKID IS '【系统提供】操作人所属公司，几乎全部查询的where条件都要加上这个条件，默认由框架自动填充（取当前所在公司），开发人员可以手工覆盖';

-- ----------------------------
-- Indexes structure for table PLT_BASE_CODE_RULE_DETAIL
-- ----------------------------
CREATE INDEX PLT_BASE_CODE_RULE_DETAIL_IDX1 ON PLT_BASE_CODE_RULE_DETAIL (HEAD_PKID);
CREATE INDEX PLT_BASE_CODE_RULE_DETAIL_IDX2 ON PLT_BASE_CODE_RULE_DETAIL (FLAG_DELETE);
CREATE INDEX PLT_BASE_CODE_RULE_DETAIL_IDX3 ON PLT_BASE_CODE_RULE_DETAIL (FLAG_SORT);
CREATE INDEX PLT_BASE_CODE_RULE_DETAIL_IDX4 ON PLT_BASE_CODE_RULE_DETAIL (FLAG_VERSION);

-- ----------------------------
-- Checks structure for table PLT_BASE_CODE_RULE_DETAIL
-- ----------------------------
ALTER TABLE PLT_BASE_CODE_RULE_DETAIL ADD CHECK (PKID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PLT_BASE_CODE_RULE_DETAIL
-- ----------------------------
ALTER TABLE PLT_BASE_CODE_RULE_DETAIL ADD PRIMARY KEY (PKID);





-- ----------------------------
-- Table structure for PLT_BASE_CODE_RULE_SERIAL
-- ----------------------------
CREATE TABLE PLT_BASE_CODE_RULE_SERIAL (
  PKID VARCHAR2(32 BYTE) NOT NULL ,
  HEAD_PKID VARCHAR2(32 BYTE) NULL ,
  SERIAL_UNION_VALUE VARCHAR2(200 BYTE) NULL ,
  SERIAL_UNION_VALUE_FORMAT VARCHAR2(200 BYTE) NULL ,
  SHOW_UNION_VALUE VARCHAR2(200 BYTE) NULL ,
  SHOW_UNION_VALUE_FORMAT VARCHAR2(200 BYTE) NULL ,
  CODE_MAX_VALUE NUMBER(20) NULL ,
  EXT0 VARCHAR2(40 BYTE) NULL ,
  EXT1 VARCHAR2(200 BYTE) NULL ,
  FLAG_STATUS NUMBER(4) NULL ,
  FLAG_SORT NUMBER(20) NULL ,
  FLAG_DELETE NUMBER(4) NULL ,
  FLAG_DELETE_TOKEN VARCHAR2(32 BYTE) DEFAULT '0',
  FLAG_VERSION NUMBER(20) NULL ,
  FLAG_AUDIT NUMBER(4) NULL ,
  AUDIT_PID VARCHAR2(40 BYTE) NULL ,
  MAKE_USER VARCHAR2(32 BYTE) NULL ,
  MAKE_TIME DATE NULL ,
  MODIFY_USER VARCHAR2(32 BYTE) NULL ,
  MODIFY_TIME DATE NULL ,
  COMP_PKID VARCHAR2(32 BYTE) NULL ,
  SYSTEM_CODE VARCHAR2(32 BYTE) NULL ,
  MODULE_CODE VARCHAR2(32 BYTE) NULL
);
COMMENT ON TABLE PLT_BASE_CODE_RULE_SERIAL IS '平台-基础数据管理-编码规则-子表2-流水';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.PKID IS '主键';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.HEAD_PKID IS '编码规则主表主键';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.SERIAL_UNION_VALUE IS '流水依据联合值，该值存储除流水号段类型之外所有段值拼接结果';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.SERIAL_UNION_VALUE_FORMAT IS '流水依据联合制格式';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.SHOW_UNION_VALUE IS '显示联合值(处理- 子表规则显示不显示业务)';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.SHOW_UNION_VALUE_FORMAT IS '显示联合值格式(处理- 子表规则显示不显示业务)';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.CODE_MAX_VALUE IS '下一个编码（流水号）值';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.EXT0 IS '扩展0';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.EXT1 IS '扩展1';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.FLAG_STATUS IS '【系统提供】默认有效，有效状态（封存状态、启用状态）。0-无效；1-有效。还可以扩展其他值，默认由框架自动填充为1，开发人员可以手工覆盖。';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.FLAG_SORT IS '【系统提供】自定义排序字段，整数，需要手工排序时使用';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.FLAG_DELETE IS '【系统提供】逻辑删除标记，0-正常；1-逻辑删除。几乎全部查询的where条件都要加上这个条件，默认由框架自动填充为0，开发人员可以手工覆盖';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.FLAG_DELETE_TOKEN IS '删除标记位';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.FLAG_VERSION IS '【系统提供】用于并发修改控制，可以存时间戳';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.FLAG_AUDIT IS '【系统提供】审核标识。-1-废弃；0-没进入审核；1-审核中；2-审核通过；3-审核未通过';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.AUDIT_PID IS '【系统提供】记录审核流中流程实例id，方便查询。工作流引擎负责写入，不用开发人员维护';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.MAKE_USER IS '【系统提供】由框架自动填充当前登录人pk_id';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.MAKE_TIME IS '【系统提供】由框架自动填充当前系统时间';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.MODIFY_USER IS '【系统提供】由框架自动填充当前登录人pk_id';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.MODIFY_TIME IS '【系统提供】由框架自动填充当前系统时间';
COMMENT ON COLUMN PLT_BASE_CODE_RULE_SERIAL.COMP_PKID IS '【系统提供】操作人所属公司，几乎全部查询的where条件都要加上这个条件，默认由框架自动填充（取当前所在公司），开发人员可以手工覆盖';

-- ----------------------------
-- Indexes structure for table PLT_BASE_CODE_RULE_SERIAL
-- ----------------------------
CREATE INDEX PLT_BASE_CODE_RULE_SERIAL_IDX1 ON PLT_BASE_CODE_RULE_SERIAL (HEAD_PKID);
CREATE INDEX PLT_BASE_CODE_RULE_SERIAL_IDX2 ON PLT_BASE_CODE_RULE_SERIAL (SERIAL_UNION_VALUE);
CREATE INDEX PLT_BASE_CODE_RULE_SERIAL_IDX3 ON PLT_BASE_CODE_RULE_SERIAL (SHOW_UNION_VALUE);
CREATE INDEX PLT_BASE_CODE_RULE_SERIAL_IDX4 ON PLT_BASE_CODE_RULE_SERIAL (FLAG_DELETE);
CREATE INDEX PLT_BASE_CODE_RULE_SERIAL_IDX5 ON PLT_BASE_CODE_RULE_SERIAL (FLAG_VERSION);

-- ----------------------------
-- Checks structure for table PLT_BASE_CODE_RULE_SERIAL
-- ----------------------------
ALTER TABLE PLT_BASE_CODE_RULE_SERIAL ADD CHECK (PKID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PLT_BASE_CODE_RULE_SERIAL
-- ----------------------------
ALTER TABLE PLT_BASE_CODE_RULE_SERIAL ADD PRIMARY KEY (PKID);

-- ----------------------------
-- Unique Union Index structure for table PLT_BASE_CODE_RULE_SERIAL
-- ----------------------------
ALTER TABLE PLT_BASE_CODE_RULE_SERIAL ADD CONSTRAINT PLT_BASE_CODE_RULE_SERIAL_CST1 UNIQUE (HEAD_PKID, SERIAL_UNION_VALUE, SHOW_UNION_VALUE, FLAG_DELETE_TOKEN);


-- ----------------------------
-- Test: Records of PLT_BASE_CODE_RULE
-- ----------------------------
INSERT INTO PLT_BASE_CODE_RULE (PKID, RULE_CODE, RULE_NAME, BELONG_BUSINESS, CODE_TYPE, EFFECTIVE_DATE, EXPIRATION_DATE , BELONG_ORG_PKID ,SYSTEM_CODE ,EXT0 ,EXT1 ,REMARK ,FLAG_STATUS ,FLAG_SORT ,FLAG_DELETE ,FLAG_DELETE_TOKEN ,FLAG_VERSION ,FLAG_AUDIT ,AUDIT_PID ,MAKE_USER ,MAKE_TIME ,MODIFY_USER ,MODIFY_TIME ,COMP_PKID ,MODULE_CODE)
VALUES ('8a80cb81608cf90001608cf90ceb0000', 'test-code', 'test-name', '1', '1', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '010011', 'MES', null, null, null, null, null, '0', '0', '0', null, null, null, TO_DATE('2017-12-25 17:20:20', 'YYYY-MM-DD HH24:MI:SS'), null, TO_DATE('2017-12-25 17:20:20', 'YYYY-MM-DD HH24:MI:SS'), null, null);

-- ----------------------------
-- Test: Records of PLT_BASE_CODE_RULE_DETAIL
-- ----------------------------
INSERT INTO PLT_BASE_CODE_RULE_DETAIL (PKID, HEAD_PKID, SECTION_TYPE, SECTION_VALUE, SECTION_LENGTH, SUPPLY_TYPE, SUPPLY_CHAR, DATE_FORMAT, FLAG_SERIAL, FLAG_SHOW, SECTION_SEPARATOR, EXT0, EXT1, FLAG_STATUS, FLAG_SORT, FLAG_DELETE, FLAG_DELETE_TOKEN, FLAG_VERSION, FLAG_AUDIT, AUDIT_PID, MAKE_USER, MAKE_TIME, MODIFY_USER, MODIFY_TIME, COMP_PKID, SYSTEM_CODE, MODULE_CODE)
VALUES ('8a80cb81608cf90001608cf90cfe0002', '8a80cb81608cf90001608cf90ceb0000', '2', 'system.current.date', '6', '8a80cb81608cf90001608cf90cfe0003', null, 'YYYYMM', '1', '1', '-', null, null, null, '2', '1', '0', '0', null, null, null, TO_DATE('2017-12-25 17:20:20', 'YYYY-MM-DD HH24:MI:SS'), null, TO_DATE('2017-12-25 17:20:20', 'YYYY-MM-DD HH24:MI:SS'), null, null, null);
INSERT INTO PLT_BASE_CODE_RULE_DETAIL (PKID, HEAD_PKID, SECTION_TYPE, SECTION_VALUE, SECTION_LENGTH, SUPPLY_TYPE, SUPPLY_CHAR, DATE_FORMAT, FLAG_SERIAL, FLAG_SHOW, SECTION_SEPARATOR, EXT0, EXT1, FLAG_STATUS, FLAG_SORT, FLAG_DELETE, FLAG_DELETE_TOKEN, FLAG_VERSION, FLAG_AUDIT, AUDIT_PID, MAKE_USER, MAKE_TIME, MODIFY_USER, MODIFY_TIME, COMP_PKID, SYSTEM_CODE, MODULE_CODE)
VALUES ('8a80cb81608cf90001608cf90cfe0003', '8a80cb81608cf90001608cf90ceb0000', '3', 'SCDD.Col1', '4', '1', null, null, '1', '1', '-', null, null, null, '3', '0', '0', '0', null, null, null, TO_DATE('2017-12-25 17:20:20', 'YYYY-MM-DD HH24:MI:SS'), null, TO_DATE('2017-12-25 17:20:20', 'YYYY-MM-DD HH24:MI:SS'), null, null, null);
INSERT INTO PLT_BASE_CODE_RULE_DETAIL (PKID, HEAD_PKID, SECTION_TYPE, SECTION_VALUE, SECTION_LENGTH, SUPPLY_TYPE, SUPPLY_CHAR, DATE_FORMAT, FLAG_SERIAL, FLAG_SHOW, SECTION_SEPARATOR, EXT0, EXT1, FLAG_STATUS, FLAG_SORT, FLAG_DELETE, FLAG_DELETE_TOKEN, FLAG_VERSION, FLAG_AUDIT, AUDIT_PID, MAKE_USER, MAKE_TIME, MODIFY_USER, MODIFY_TIME, COMP_PKID, SYSTEM_CODE, MODULE_CODE)
VALUES ('8a80cb81608cf90001608cf90cfd0001', '8a80cb81608cf90001608cf90ceb0000', '1', 'SCDD', '4', '0', null, null, '1', '1', '-', null, null, null, '1', '0', '0', '0', null, null, null, TO_DATE('2017-12-25 17:20:20', 'YYYY-MM-DD HH24:MI:SS'), null, TO_DATE('2017-12-25 17:20:20', 'YYYY-MM-DD HH24:MI:SS'), null, null, null);
INSERT INTO PLT_BASE_CODE_RULE_DETAIL (PKID, HEAD_PKID, SECTION_TYPE, SECTION_VALUE, SECTION_LENGTH, SUPPLY_TYPE, SUPPLY_CHAR, DATE_FORMAT, FLAG_SERIAL, FLAG_SHOW, SECTION_SEPARATOR, EXT0, EXT1, FLAG_STATUS, FLAG_SORT, FLAG_DELETE, FLAG_DELETE_TOKEN, FLAG_VERSION, FLAG_AUDIT, AUDIT_PID, MAKE_USER, MAKE_TIME, MODIFY_USER, MODIFY_TIME, COMP_PKID, SYSTEM_CODE, MODULE_CODE)
VALUES ('8a80cb81608cf90001608cf90cfe0004', '8a80cb81608cf90001608cf90ceb0000', '6', null, '4', '1', '0', null, '0', '1', null, null, null, null, '4', '0', '0', '0', null, null, null, TO_DATE('2017-12-25 17:20:20', 'YYYY-MM-DD HH24:MI:SS'), null, TO_DATE('2017-12-25 17:20:20', 'YYYY-MM-DD HH24:MI:SS'), null, null, null);
